#!/bin/bash

(
allStatusText="$(alldirs git status . 2>&1 | grep -vi 'permission denied')"
diff <(echo "${allStatusText}" | grep 'nothing to commit' -B 4 -A 1) <(echo "${allStatusText}") | grep -E '^|>>>.*|modified' --color=always
[[ "0" -eq "$?" ]] && exit 1 || exit 0
)

