#!/bin/bash
#

testClass="$1"

(
    set -x
    find . -wholename '*surefire-reports/'"$testClass"'*' | grep -v 'surefire-reports/TEST' \
    | xargs wc -l | awk '$1 > 4 { printf $2 "\n" }' | grep -v 'total' | xargs cat
)
