#!/bin/bash

if [[ "$#" -lt 2 ]]
then
  exec 1>&2
  echo 'usage: '"$0"' PATH [enable | disable]'
else
  #fsutil.exe file setCaseSensitiveInfo "$1" "$2"
  find "$1" -type d -print0 | xargs -0 -L1 -I '{}' fscs '{}' "$2"
fi

