#!/bin/bash
#

(
try_count=1
until (echo 'Try #'"$try_count" && set -x && exec "$@") 
do
    try_count=$((try_count+1))
    echo ''
    echo '===== Failed, trying again. ====='
    echo ''
    echo ''
    sleep 0.5
done
)

